# Generated by Django 5.0.14 on 2026-05-07 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspace_default_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('location_type', models.CharField(choices=[('storage', 'Storage'), ('receiving', 'Receiving'), ('dispatch', 'Dispatch'), ('adjustment', 'Adjustment'), ('other', 'Other')], default='storage', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.warehouse')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_locations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['warehouse__name', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['workspace', 'code'], name='warehouse_w_workspa_e1ae95_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['workspace', 'status'], name='warehouse_w_workspa_445f62_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='unique_warehouse_code_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['workspace', 'warehouse'], name='warehouse_w_workspa_635cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['workspace', 'warehouse', 'code'], name='warehouse_w_workspa_b33fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['workspace', 'status'], name='warehouse_w_workspa_3340df_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('workspace', 'warehouse', 'code'), name='unique_location_code_per_workspace_warehouse'),
        ),
    ]
