# Generated by Django 5.0.14 on 2026-05-07 16:57

import django.db.models.deletion
import uuid
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subdomain', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], max_length=20)),
                ('token', models.CharField(default=workspaces.models.generate_invite_token, editable=False, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(default=workspaces.models.default_invite_expiration)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_workspace_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_workspace_invites', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('disabled', 'Disabled')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_workspace_membership_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'user__email'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['subdomain', 'status'], name='workspaces__subdoma_6b39a4_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='workspaces__slug_b5cc60_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['workspace', 'email'], name='workspaces__workspa_6d2690_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['status'], name='workspaces__status_15dd09_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['expires_at'], name='workspaces__expires_276286_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'status'], name='workspaces__workspa_205f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['user', 'status'], name='workspaces__user_id_074457_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['role'], name='workspaces__role_3baebc_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_membership'),
        ),
    ]
