# Generated by Django 5.0.14 on 2026-05-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='default_timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='workspace',
            name='low_stock_dashboard_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
