# Generated by Django 5.0.14 on 2026-05-07 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('workspaces', '0002_workspace_default_timezone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('transfer_batch_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_stock_movements', to='warehouse.warehouselocation')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_stock_movements', to='warehouse.warehouse')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_movements', to='warehouse.warehouselocation')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_stock_movements', to='warehouse.warehouse')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='warehouse.warehouselocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='warehouse.warehouse')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['product__sku', 'warehouse__code', 'location__code'],
                'indexes': [models.Index(fields=['workspace', 'product'], name='inventory_s_workspa_d69e20_idx'), models.Index(fields=['workspace', 'warehouse'], name='inventory_s_workspa_f9d44c_idx'), models.Index(fields=['workspace', 'warehouse', 'location'], name='inventory_s_workspa_0327ba_idx'), models.Index(fields=['workspace', 'product', 'warehouse', 'location'], name='inventory_s_workspa_267d56_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('workspace', 'product', 'warehouse', 'location'), name='unique_stock_level_per_product_location'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='stock_level_quantity_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['workspace', 'product'], name='inventory_s_workspa_d27a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['workspace', 'movement_type'], name='inventory_s_workspa_6e30b6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['workspace', 'created_at'], name='inventory_s_workspa_d314f2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['workspace', 'source_warehouse'], name='inventory_s_workspa_106df5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['workspace', 'destination_warehouse'], name='inventory_s_workspa_20a091_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'),
        ),
    ]
